import re
import sys

if len(sys.argv) >= 3:
    outfile_name = sys.argv[2]
    outfile = open(outfile_name,"a",encoding="utf-8")
else:
    outfile_name = "output.bib"
    outfile = open(outfile_name,"w",encoding="utf-8")
    outfile.write("!TEX root = main.tex\n")
    outfile.write("% Encoding: UTF-8\n")
    outfile.write("% Generated by prettybib.py\n\n")
with open(sys.argv[1],"r",encoding="utf-8") as infile:
    for line in infile:
        if "@" in line:
            line = re.sub(r"{(.*?)_",r"{\1:",line)
            outfile.write(line)
        elif "author" in line:
            outfile.write(line)
        elif re.search(r"\btitle\b",line) != None:
            outfile.write(line)
        elif "booktitle" in line or "journaltitle" in line:
            # line = line.replace("eventtitle","booktitle")
            outfile.write(line)
        elif re.search(r"\bdate\b",line) != None:
            line = re.sub(r"([0-9]{4})-[0-9]{2}-[0-9]{2}",r"\1",line)
            line = line.replace("date","year")
            outfile.write(line)
        elif line[0] == "}":
            outfile.write("}\n\n")
outfile.close()